// @vitest-environment node
// Integration proof that the REAL @techstark/opencv-js is loaded and invoked
// (not mocked). All fixtures are SYNTHETIC — generated by opencv itself, no
// camera. Runs in the node environment so opencv.js initializes cleanly.
import { createRequire } from "node:module";
import { describe, expect, it, beforeAll } from "vitest";
import { applyHomography, reprojectionError, solveHomography, type Point } from "./homography";
import {
  CHARUCO_BOARD,
  charucoAvailable,
  charucoCornerTarget,
  charucoHomography,
  detectCharuco,
  findHomographyCv,
  perspectiveTransformCv,
  waitForOpenCvRuntime,
  type OpenCvModule,
} from "./opencvCalib";

// Load the REAL opencv.js via CJS require (not ESM import): opencv's Emscripten
// export carries a `then`, which makes vitest's ESM runner try to assimilate the
// module namespace as a thenable. createRequire sidesteps that entirely.
const require = createRequire(import.meta.url);

let cv: OpenCvModule;
beforeAll(async () => {
  const raw = require("@techstark/opencv-js") as OpenCvModule;
  cv = await waitForOpenCvRuntime(raw);
}, 60_000);

const UNIT_SQUARE: Point[] = [
  { x: 0, y: 0 },
  { x: 1, y: 0 },
  { x: 1, y: 1 },
  { x: 0, y: 1 },
];

describe("opencv.js homography (real cv.getPerspectiveTransform) [synthetic]", () => {
  const imgCorners: Point[] = [
    { x: 120, y: 80 },
    { x: 900, y: 60 },
    { x: 950, y: 640 },
    { x: 90, y: 700 },
  ];

  it("maps its 4 calibration corners with reprojection error ≈ 0", () => {
    const H = perspectiveTransformCv(cv, imgCorners, UNIT_SQUARE);
    expect(reprojectionError(H, imgCorners, UNIT_SQUARE)).toBeLessThan(1e-6);
  });

  it("agrees with the pure-TS solver on an interior point (cross-check)", () => {
    const cvH = perspectiveTransformCv(cv, imgCorners, UNIT_SQUARE);
    const tsH = solveHomography(imgCorners, UNIT_SQUARE);
    const p: Point = { x: 500, y: 400 };
    const a = applyHomography(cvH, p);
    const b = applyHomography(tsH, p);
    expect(a.x).toBeCloseTo(b.x, 6);
    expect(a.y).toBeCloseTo(b.y, 6);
  });
});

describe("ChArUco pipeline (real cv.aruco_*) [synthetic board]", () => {
  it("reports ChArUco as available in this build", () => {
    expect(charucoAvailable(cv)).toBe(true);
  });

  it("generates a board, detects all 12 corners, solves a homography with small reprojection", () => {
    // Generate the synthetic board with opencv itself (no camera).
    const dict = cv.getPredefinedDictionary(cv.DICT_4X4_50);
    const board = new cv.aruco_CharucoBoard!(
      new cv.Size(CHARUCO_BOARD.squaresX, CHARUCO_BOARD.squaresY),
      CHARUCO_BOARD.squareLength,
      CHARUCO_BOARD.markerLength,
      dict,
      new cv.Mat(),
    ) as unknown as { generateImage(size: object, out: object, m: number, b: number): void; delete(): void };
    const img = new cv.Mat();
    board.generateImage(new cv.Size(1000, 800), img as unknown as object, 20, 1);

    const det = detectCharuco(cv, img as never);
    expect(det.imageCorners.length).toBe(CHARUCO_BOARD.cornersX * CHARUCO_BOARD.cornersY); // 12
    expect(det.ids.slice().sort((a, b) => a - b)).toEqual([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]);

    const targets = det.ids.map(charucoCornerTarget);
    const H = findHomographyCv(cv, det.imageCorners, targets);
    expect(reprojectionError(H, det.imageCorners, targets)).toBeLessThan(0.02); // normalized units

    const wrapped = charucoHomography(cv, img as never);
    expect(wrapped).not.toBeNull();
    expect(wrapped!.homographyConf).toBeCloseTo(1, 6);
    expect(wrapped!.cornersDetected).toBe(12);

    (img as unknown as { delete(): void }).delete();
    board.delete();
  });
});
